// <auto-generated />
namespace CMS.Migrations.ApplicationUsers
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialAppUserMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialAppUserMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201712221313079_initial AppUser Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
